name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: bun install

      - name: Format check
        run: bun check

      - name: Lint
        run: bun lint

      - name: Build
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/syncopate"
        run: bun run build

      - name: Test
        run: bun run --filter "*" test
